-- Products catalog managed from the site's admin area.
-- Run once (safe to re-run): creates the table, access rules, the image
-- storage bucket, and copies in the products the site showed before.

create table if not exists public.products (
  id text primary key default gen_random_uuid()::text,
  category text not null,
  name_he text not null default '',
  name_fr text not null default '',
  name_en text not null default '',
  subtitle_he text not null default '',
  subtitle_fr text not null default '',
  subtitle_en text not null default '',
  description_he text not null default '',
  description_fr text not null default '',
  description_en text not null default '',
  price numeric(10,2) not null check (price >= 0),
  images text[] not null default '{}',
  active boolean not null default true,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists products_category_idx on public.products (category, sort);

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant all on public.products to service_role;
alter table public.products enable row level security;

drop policy if exists "anyone reads active products" on public.products;
create policy "anyone reads active products" on public.products for select to anon, authenticated
  using (active or public.has_role(auth.uid(), 'admin'));
drop policy if exists "admins insert products" on public.products;
create policy "admins insert products" on public.products for insert to authenticated
  with check (public.has_role(auth.uid(), 'admin'));
drop policy if exists "admins update products" on public.products;
create policy "admins update products" on public.products for update to authenticated
  using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));
drop policy if exists "admins delete products" on public.products;
create policy "admins delete products" on public.products for delete to authenticated
  using (public.has_role(auth.uid(), 'admin'));

-- Public bucket for product photos; only admins may upload, replace or delete.
insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true)
  on conflict (id) do nothing;
drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects for insert to authenticated
  with check (bucket_id = 'product-images' and public.has_role(auth.uid(), 'admin'));
drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects for update to authenticated
  using (bucket_id = 'product-images' and public.has_role(auth.uid(), 'admin'));
drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects for delete to authenticated
  using (bucket_id = 'product-images' and public.has_role(auth.uid(), 'admin'));

-- Products the site showed before the catalog moved to the database.
insert into public.products
  (id, category, name_he, name_fr, name_en, subtitle_he, subtitle_fr, subtitle_en,
   description_he, description_fr, description_en, price, images, sort)
values
  ('rosh-hashana-candles', 'rosh-hashana', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 385, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('rosh-hashana-perfume', 'rosh-hashana', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 690, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('rosh-hashana-jewelry', 'rosh-hashana', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1020, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('rosh-hashana-shabbat', 'rosh-hashana', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 550, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('rosh-hashana-sweets', 'rosh-hashana', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 205, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('rosh-hashana-book', 'rosh-hashana', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 305, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('rosh-hashana-baby', 'rosh-hashana', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 340, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('rosh-hashana-signature', 'rosh-hashana', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 500, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('sukkot-candles', 'sukkot', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 395, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('sukkot-perfume', 'sukkot', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 640, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('sukkot-jewelry', 'sukkot', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1030, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('sukkot-shabbat', 'sukkot', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 560, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('sukkot-sweets', 'sukkot', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 215, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('sukkot-book', 'sukkot', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 315, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('sukkot-baby', 'sukkot', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 350, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('sukkot-signature', 'sukkot', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 450, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('hanukkah-candles', 'hanukkah', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 405, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('hanukkah-perfume', 'hanukkah', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 650, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('hanukkah-jewelry', 'hanukkah', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 980, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('hanukkah-shabbat', 'hanukkah', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 570, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('hanukkah-sweets', 'hanukkah', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 225, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('hanukkah-book', 'hanukkah', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 325, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('hanukkah-baby', 'hanukkah', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 360, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('hanukkah-signature', 'hanukkah', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 460, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('tu-bishvat-candles', 'tu-bishvat', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 415, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('tu-bishvat-perfume', 'tu-bishvat', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 660, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('tu-bishvat-jewelry', 'tu-bishvat', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 990, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('tu-bishvat-shabbat', 'tu-bishvat', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 520, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('tu-bishvat-sweets', 'tu-bishvat', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 235, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('tu-bishvat-book', 'tu-bishvat', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 335, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('tu-bishvat-baby', 'tu-bishvat', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 370, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('tu-bishvat-signature', 'tu-bishvat', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 470, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('purim-candles', 'purim', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 425, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('purim-perfume', 'purim', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 670, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('purim-jewelry', 'purim', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1000, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('purim-shabbat', 'purim', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 530, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('purim-sweets', 'purim', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 185, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('purim-book', 'purim', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 345, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('purim-baby', 'purim', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 380, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('purim-signature', 'purim', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 480, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('pesach-candles', 'pesach', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 435, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('pesach-perfume', 'pesach', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 680, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('pesach-jewelry', 'pesach', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1010, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('pesach-shabbat', 'pesach', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 540, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('pesach-sweets', 'pesach', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 195, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('pesach-book', 'pesach', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 295, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('pesach-baby', 'pesach', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 390, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('pesach-signature', 'pesach', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 490, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('shavuot-candles', 'shavuot', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 385, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('shavuot-perfume', 'shavuot', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 690, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('shavuot-jewelry', 'shavuot', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1020, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('shavuot-shabbat', 'shavuot', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 550, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('shavuot-sweets', 'shavuot', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 205, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('shavuot-book', 'shavuot', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 305, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('shavuot-baby', 'shavuot', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 340, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('shavuot-signature', 'shavuot', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 500, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('shabbat-candles', 'shabbat', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 395, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('shabbat-perfume', 'shabbat', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 640, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('shabbat-jewelry', 'shabbat', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1030, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('shabbat-shabbat', 'shabbat', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 560, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('shabbat-sweets', 'shabbat', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 215, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('shabbat-book', 'shabbat', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 315, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('shabbat-baby', 'shabbat', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 350, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('shabbat-signature', 'shabbat', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 450, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('birthday-child-candles', 'birthday-child', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 405, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('birthday-child-perfume', 'birthday-child', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 650, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('birthday-child-jewelry', 'birthday-child', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 980, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('birthday-child-shabbat', 'birthday-child', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 570, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('birthday-child-sweets', 'birthday-child', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 225, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('birthday-child-book', 'birthday-child', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 325, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('birthday-child-baby', 'birthday-child', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 360, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('birthday-child-signature', 'birthday-child', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 460, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('birthday-teen-candles', 'birthday-teen', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 415, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('birthday-teen-perfume', 'birthday-teen', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 660, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('birthday-teen-jewelry', 'birthday-teen', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 990, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('birthday-teen-shabbat', 'birthday-teen', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 520, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('birthday-teen-sweets', 'birthday-teen', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 235, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('birthday-teen-book', 'birthday-teen', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 335, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('birthday-teen-baby', 'birthday-teen', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 370, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('birthday-teen-signature', 'birthday-teen', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 470, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('birthday-adult-candles', 'birthday-adult', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 425, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('birthday-adult-perfume', 'birthday-adult', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 670, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('birthday-adult-jewelry', 'birthday-adult', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1000, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('birthday-adult-shabbat', 'birthday-adult', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 530, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('birthday-adult-sweets', 'birthday-adult', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 185, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('birthday-adult-book', 'birthday-adult', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 345, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('birthday-adult-baby', 'birthday-adult', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 380, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('birthday-adult-signature', 'birthday-adult', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 480, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('baby-candles', 'baby', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 435, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('baby-perfume', 'baby', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 680, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('baby-jewelry', 'baby', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1010, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('baby-shabbat', 'baby', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 540, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('baby-sweets', 'baby', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 195, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('baby-book', 'baby', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 295, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('baby-baby', 'baby', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 390, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('baby-signature', 'baby', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 490, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('bar-mitzvah-candles', 'bar-mitzvah', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 385, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('bar-mitzvah-perfume', 'bar-mitzvah', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 690, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('bar-mitzvah-jewelry', 'bar-mitzvah', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1020, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('bar-mitzvah-shabbat', 'bar-mitzvah', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 550, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('bar-mitzvah-sweets', 'bar-mitzvah', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 205, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('bar-mitzvah-book', 'bar-mitzvah', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 305, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('bar-mitzvah-baby', 'bar-mitzvah', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 340, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('bar-mitzvah-signature', 'bar-mitzvah', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 500, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('bat-mitzvah-candles', 'bat-mitzvah', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 395, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('bat-mitzvah-perfume', 'bat-mitzvah', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 640, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('bat-mitzvah-jewelry', 'bat-mitzvah', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1030, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('bat-mitzvah-shabbat', 'bat-mitzvah', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 560, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('bat-mitzvah-sweets', 'bat-mitzvah', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 215, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('bat-mitzvah-book', 'bat-mitzvah', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 315, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('bat-mitzvah-baby', 'bat-mitzvah', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 350, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('bat-mitzvah-signature', 'bat-mitzvah', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 450, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('judaica-candles', 'judaica', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 405, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('judaica-perfume', 'judaica', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 650, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('judaica-jewelry', 'judaica', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 980, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('judaica-shabbat', 'judaica', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 570, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('judaica-sweets', 'judaica', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 225, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('judaica-book', 'judaica', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 325, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('judaica-baby', 'judaica', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 360, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('judaica-signature', 'judaica', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 460, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('for-boy-candles', 'for-boy', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 415, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('for-boy-perfume', 'for-boy', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 660, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('for-boy-jewelry', 'for-boy', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 990, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('for-boy-shabbat', 'for-boy', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 520, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('for-boy-sweets', 'for-boy', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 235, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('for-boy-book', 'for-boy', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 335, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('for-boy-baby', 'for-boy', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 370, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('for-boy-signature', 'for-boy', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 470, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7),
  ('for-girl-candles', 'for-girl', 'זוג פמוטי זהב מגולפים', 'Paire de bougeoirs dorés', 'Pair of gilded candlesticks', 'פליז מוזהב · 24 ס״מ', 'Laiton doré · 24 cm', 'Gilded brass · 24 cm', 'זוג פמוטים מפליז מוזהב בעיטור ידני, ארוזים בקופסת מתנה עם סרט זהב. מתנה שנשארת על השולחן שנים.', 'Une paire de bougeoirs en laiton doré, ciselés à la main, présentés dans un coffret au ruban doré. Un cadeau qui reste sur la table pendant des années.', 'A pair of hand-chased gilded brass candlesticks in a gift box with a gold ribbon. A gift that stays on the table for years.', 425, array['/products/candlesticks.jpg', '/products/hero-gift.jpg', '/products/sweets.jpg'], 0),
  ('for-girl-perfume', 'for-girl', 'בושם קריסטל ״זהב טהור״', 'Parfum cristal « Or pur »', 'Crystal perfume ''Pure Gold''', '30 מ״ל · קופסת מתנה', '30 ml · coffret cadeau', '30 ml · gift box', 'בקבוק קריסטל מלוטש עם פקק זהב, ניחוח פרחוני עדין עם בסיס וניל ועץ אגוז. מגיע בקופסת עור כחולה.', 'Flacon en cristal taillé au bouchon doré, fragrance florale délicate sur fond de vanille et de bois. Livré dans un coffret en cuir bleu.', 'Cut-crystal bottle with a gold cap, a delicate floral scent over vanilla and wood. Arrives in a blue leather case.', 670, array['/products/perfume.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 1),
  ('for-girl-jewelry', 'for-girl', 'סט תכשיטי זהב עם יהלומון', 'Parure en or et diamant', 'Gold jewelry set with diamond', 'זהב 14 קראט · תעודה', 'Or 14 carats · certificat', '14k gold · certificate', 'שרשרת ועגילים תואמים בעבודת פיליגרן עדינה, משובצים יהלומון. מגיעים בקופסת עץ עם תעודת אחריות.', 'Collier et boucles d''oreilles assortis en filigrane délicat, sertis d''un petit diamant. Coffret en bois et certificat inclus.', 'Matching necklace and earrings in delicate filigree, set with a small diamond. Wooden case and certificate included.', 1000, array['/products/jewelry.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 2),
  ('for-girl-shabbat', 'for-girl', 'מארז שבת מהודר', 'Coffret Chabbat d''exception', 'Deluxe Shabbat set', 'גביע קידוש ומפת חלה', 'Coupe de Kiddouch et couvre-halla', 'Kiddush cup and challah cover', 'גביע קידוש מכסף ומפת חלה מקטיפה רקומה, מונחים בקופסת עץ מרופדת. מארז שמביא את השבת הביתה.', 'Coupe de Kiddouch en argent et couvre-halla en velours brodé, dans un coffret en bois doublé. Le Chabbat à la maison.', 'Silver Kiddush cup and embroidered velvet challah cover in a lined wooden case. Shabbat, delivered.', 530, array['/products/shabbat-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 3),
  ('for-girl-sweets', 'for-girl', 'מארז פרלינים מוזהב', 'Coffret de pralines dorées', 'Gilded praline box', '12 פרלינים · שוקולד בלגי', '12 pralines · chocolat belge', '12 pralines · Belgian chocolate', 'שתים-עשרה פרלינים בעבודת יד עטופים בנייר זהב, בקופסה כחולה עם סרט. מתאים לכל גיל ולכל אירוע.', 'Douze pralines artisanales enveloppées d''or, dans un coffret bleu à ruban. Pour tous les âges et toutes les occasions.', 'Twelve handmade pralines wrapped in gold foil, in a blue ribboned box. Right for any age and any occasion.', 185, array['/products/sweets.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg'], 4),
  ('for-girl-book', 'for-girl', 'סידור עור עם הקדשה', 'Livre de prières en cuir gravé', 'Leather prayer book, engraved', 'עור אמיתי · חריטת שם', 'Cuir véritable · gravure', 'Real leather · name engraving', 'סידור בכריכת עור חומה עם אותיות זהב וסימנייה, כולל חריטת שם אישית על הכריכה.', 'Livre relié en cuir brun, lettres dorées et marque-page, avec gravure du prénom sur la couverture.', 'Brown leather binding with gold lettering and a ribbon marker, including personal name engraving.', 345, array['/products/book.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 5),
  ('for-girl-baby', 'for-girl', 'מארז ברוך הבא לתינוק', 'Coffret bienvenue bébé', 'Welcome baby set', 'שמיכת צמר ורעשן כסף', 'Couverture et hochet argenté', 'Knit blanket and silver rattle', 'שמיכת צמר סרוגה ברכות ורעשן כסף מגולף, מונחים בקופסה כחולה עם סרט זהב וכרטיס ברכה.', 'Couverture tricotée toute douce et hochet en argent ciselé, dans un coffret bleu au ruban doré avec carte.', 'Softly knitted blanket and an engraved silver rattle in a blue box with gold ribbon and a card.', 380, array['/products/baby-set.jpg', '/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 6),
  ('for-girl-signature', 'for-girl', 'מארז החתימה שלנו', 'Notre coffret signature', 'Our signature box', 'בושם, תכשיט וכרטיס', 'Parfum, bijou et carte', 'Perfume, jewel and card', 'מארז החתימה של הבית: בושם קטן, תכשיט עדין וכרטיס ברכה בכתב ידכם, בקופסה כחולה עם סרט זהב.', 'Le coffret signature de la maison : un petit parfum, un bijou délicat et votre carte manuscrite, dans un écrin bleu au ruban doré.', 'The house signature: a small perfume, a delicate jewel and your handwritten card, in a blue box with a gold ribbon.', 480, array['/products/hero-gift.jpg', '/products/candlesticks.jpg', '/products/sweets.jpg'], 7)
on conflict (id) do nothing;
